import argparse

from html_processor import HtmlReportBuilder
from resource_compliance_areas import ComplianceAreas
from resource_compliance_checker import ResourceComplianceChecker
from results_writer import write_outputs
from resource_filter import ResourceFilter
from resource_scanner import ResourceScanner

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Azure tag complianceCheck report.")
    parser.add_argument("-i", "--input", required=False, help="Specifies the input CSV file generated by a previous scan. Using this flag will not perform a new scan against the cloud provider resources.")
    parser.add_argument("-f", "--filter", type=str, help='Filter in the form: key=value [key=value ...]')
    parser.add_argument("-o", "--output", required=False, default="azure_resource_compliance_scan.csv", help="Specifies the file name to write scan results to (CSV format)")

    args = parser.parse_args()

    areas = ComplianceAreas()

    res_filter = ResourceFilter(args.filter)
    res_compliance = ResourceComplianceChecker(areas)

    scanner = ResourceScanner(res_filter)
    if args.input:
        scanner.load_from_file(args.input)
    else:
        scanner.scan_resources()

    print(f"📊 Calculating compliance across {len(areas)} areas...")
    res_compliance.check_compliance(scanner)

    if len(scanner) > 0:
        print('📝 Generating HTML report...')

        filter_val = res_filter.to_friendly()
        generator = HtmlReportBuilder(scanner, areas, res_compliance)
        generator.generate(scanner.scan_datetime, scanner.scan_user, filter_val)
        generator.save("scan_results.html")

    write_outputs(scanner, args.output)
