---

parameters:
- name: serviceConnection
  type: string
- name: testProjectDirectory
  type: string
- name: testProjectName
  type: string

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true

- task: DeleteFiles@1
  displayName: 'Clean Build Directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/bin/*
      **/obj/*
      **/TestResults/*
      **/drop/*
    RemoveSourceFolder: false

- task: FileTransform@1
  displayName: 'Transform Configuration Files'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/${{ parameters.testProjectDirectory }}/Config'
    fileType: 'json'
    targetFiles: '*.json'

- task: PowerShell@2
  displayName: 'Copy Test Files'
  inputs:
    targetType: 'inline'
    script: |
      $sourcePath = '$(System.DefaultWorkingDirectory)/${{ parameters.testProjectDirectory }}/TestFiles'
      $targetPath = '$(Build.ArtifactStagingDirectory)/TestFiles'

      # Check if the source directory exists
      if (!(Test-Path -Path $sourcePath)) {
        Write-Error "Source directory not found: $sourcePath"
        exit 1
      }

      # Create the target directory if it doesn't exist
      if (!(Test-Path -Path $targetPath)) {
        New-Item -ItemType Directory -Path $targetPath
      }

      # Copy the files
      Copy-Item -Path $sourcePath -Destination $targetPath -Recurse -Force

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'TestFiles'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'TestFiles'
    downloadPath: '$(System.DefaultWorkingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Build Test Framework Solution'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/${{ parameters.testProjectDirectory }}/${{ parameters.testProjectName }}.sln'
    arguments: '--configuration Release'

- script: |
    export AZURE_IDENTITY_DISABLE_MANAGED_IDENTITY=true
  displayName: 'Export Identity Config'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: '$(System.DefaultWorkingDirectory)/${{ parameters.testProjectDirectory }}/${{ parameters.testProjectName }}.csproj'
    publishTestResults: true
    connectedServiceName: ${{ parameters.serviceConnection }}
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/*.trx'
    testRunTitle: 'Tests'
    mergeTestResults: true
    createTestRun: true
    testResultFormat: VSTest
    azureSubscription: ${{ parameters.serviceConnection }}
